# Generated by Django 5.0.4 on 2024-04-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_listing_bathrooms_listing_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
