# Generated by Django 5.0.4 on 2024-04-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_listing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='description',
            new_name='back_description',
        ),
        migrations.AddField(
            model_name='listing',
            name='front_description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
