# Generated by Django 5.0.4 on 2024-04-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_description_listing_back_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='front_description',
            field=models.TextField(blank=True, max_length=251),
        ),
    ]
