# Generated by Django 5.0.4 on 2024-04-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_listing_front_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='back_description',
            field=models.TextField(blank=True, help_text='Detailed description. Long description of property', max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='front_description',
            field=models.TextField(blank=True, help_text='Listings page description. Short description of property', max_length=251),
        ),
    ]
