# Generated by Django 5.0.4 on 2024-04-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_listing_back_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='front_description',
            field=models.TextField(blank=True, help_text='Listings page description. Short description of property', max_length=100),
        ),
    ]
