# Generated by Django 5.0.4 on 2024-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Listing_Name", models.CharField(max_length=250)),
                ("Employer", models.CharField(max_length=250)),
                ("Government_Agency", models.BooleanField(blank=True)),
                ("Salary", models.CharField(blank=True, max_length=50)),
                ("Bachelors", models.CharField(blank=True, max_length=500)),
                ("Associate", models.CharField(blank=True, max_length=500)),
                ("Masters", models.CharField(blank=True, max_length=500)),
                ("Doctoral", models.CharField(blank=True, max_length=500)),
                ("Bachelors_Pay", models.CharField(blank=True, max_length=500)),
                ("Associate_Pay", models.CharField(blank=True, max_length=500)),
                ("Masters_Pay", models.CharField(blank=True, max_length=500)),
                ("Doctoral_Pay", models.CharField(blank=True, max_length=500)),
                (
                    "Experience",
                    models.CharField(
                        blank=True,
                        help_text="Number of years in experience.",
                        max_length=500,
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
