# Generated by Django 5.0.4 on 2024-05-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Location_Broad',
            field=models.CharField(blank=True, help_text='State, Territory, Country', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='Location_Local',
            field=models.CharField(blank=True, help_text='Street, City, Zip', max_length=500),
        ),
    ]
