# Generated by Django 5.0.4 on 2024-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_job_location_broad_alter_job_location_local_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="Associate_Pay",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="Bachelors_Pay",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="Doctoral_Pay",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="Masters_Pay",
            field=models.IntegerField(),
        ),
    ]
